import "./globals.css";
import { Poppins } from "next/font/google";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const poppins = Poppins({
    weight: ["400", "500", "600", "700", "800"],
    style: "normal",
    subsets: ["latin-ext"],
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body style={poppins.style}>{children}</body>
        </html>
    );
}
